trigger:
- main  # 或你的分支名

pool:
  vmImage: 'windows-latest'  # 也可用 ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'  # 或你需要的版本

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    python -m playwright install
  displayName: 'Install dependencies and Playwright browsers'

- script: |
    python PlayWright.py
  displayName: 'Run Playwright Test'

#- script: |
#    pytest test_playwright_script.py --html=report.html --self-contained-html
#  displayName: 'Run Pytest and Generate HTML Report'
#
#- task: PublishPipelineArtifact@1
#  inputs:
#    targetPath: '$(System.DefaultWorkingDirectory)/report.html'
#    artifact: 'pytest-report'
#    publishLocation: 'pipeline'
#  displayName: 'Publish Pytest HTML Report'


